<img src="https://media.licdn.com/dms/image/C561BAQEVCDe44Tt-kQ/company-background_10000/0?e=2159024400&v=beta&t=BglJGcQeWT2zCaG1sbW30jo9YOGOUCqQ6TOPnWPlra4"/>

# Numpy

We will be learning about some basic programming and data analysis using Numpy and Pandas. First up - NumPy

NumPy is the fundamental package for scientific computing in Python. It is used across many fields inc. Mathematics, Engineering, Finance, Data Science, Artificial Intelligence, Machine Learning etc. Most scientific computing libraries will build on NumPy.

Numpy provides functions to work with N-dimensional arrays and an assortment of routines for fast operations on such arrays: matrix mathematics, logical, shape manipulation, statistical operations, random simulation etc.

## Basic Numpy tools

<img src="https://matteding.github.io/images/broadcasting-3d-scalar.gif" width="400" height="400" align="left"/>


Here, we will exam some fairly simple tools in Numpy for the management of data and doing basic statistics. First, lets make sure numpy is imported:


In [1]:
import numpy as np

### Array creation and Indexing

In the cells below we will learn basic array creation and indexing


In [2]:
a = np.array([1, 2, 3])            # Create a simple array
print("Numpy Array 'a':\n")
print(type(a))                     # Prints type as recognised by Python
print(a.shape)                     # Prints its shape
print(a[0], a[1], a[2])            # Prints certain indexed values
a[0] = 5                           # Change an element of the array
print(a,"\n")                   


print("Numpy Array 'b':\n")
b = np.array([[1,2,3],[4,5,6]])    # Create an array with more 'complexity'
print(b.shape)
print(b)                     
print(b[0, 0], b[0, 1], b[1, 0])  


Numpy Array 'a':

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3] 

Numpy Array 'b':

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


### Array manipulation and mathematics
Where numpy gets really powerful is its efficiency in array manipulation and mathematics.

In [3]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y,'\n')
print(x * y,'\n') 

# numpy has many mathematical functions built in - accessed via dot notation
print(np.sqrt(x),'\n')
print(np.dot(x, y),'\n')
print(np.cross(x, y),'\n')

[[ 6  8]
 [10 12]] 

[[ 5 12]
 [21 32]] 

[[1.         1.41421356]
 [1.73205081 2.        ]] 

[[19 22]
 [43 50]] 

[-4 -4] 



Numpy also provides aggregation methods.

In [4]:
print(x.sum())  # sum over the entire matrix
print(y.mean(axis=1))  # mean of each row

10
[5.5 7.5]


#### Your turn...

In [10]:
import numpy as np
# Create the following 3 x 4 array and call it 'c':

# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

c = np.array([[ 1, 2, 3,4],
              [ 5,6,7,8],
              [ 9,10,11,12]])


In [11]:
ques_1 = c[1:3, :]
print("ques_1:\n", ques_1) # Print all values in rows 2 & 3
ques_2 = c[1, [0, 2]]
print("ques_2:\n", ques_2)   # Print the values in the 2nd row and in cols 1 & 3
ques_3 = c * 4
print("ques_3:\n", ques_3)   # perform a scalar multiplication of c with 4
ques_4 = c.T
print("ques_4 (Transpose of c):\n", ques_4)   # transpose c
ques_5 =  c.reshape(4, 3)
print("ques_5 (Reshaped c):\n", ques_5)
  # reshape c to a 4 x 3 array?
ques_6 =  ques_5 * ques_4
print("ques_6 (Element-wise multiplication of reshaped and transposed c):\n", ques_6)  # perform an element wise multiplicaton of the reshaped c and transposed c 

ques_1:
 [[ 5  6  7  8]
 [ 9 10 11 12]]
ques_2:
 [5 7]
ques_3:
 [[ 4  8 12 16]
 [20 24 28 32]
 [36 40 44 48]]
ques_4 (Transpose of c):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
ques_5 (Reshaped c):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ques_6 (Element-wise multiplication of reshaped and transposed c):
 [[  1  10  27]
 [  8  30  60]
 [ 21  56  99]
 [ 40  88 144]]


### Random
Random number generation plays a crucial role in configuring and evaluating many numerical and machine learning algorithms. Whether it's for randomly initializing weights in a neural network, splitting data into random subsets, or shuffling a dataset, the ability to generate random numbers (specifically repeatable pseudo-random numbers) is vital.

In [13]:
# create a half hourly power profile for 1 year filled with random numbers between 0 and 50
num_intervals = 365 * 24 * 2
power_profile = np.random.uniform(0, 50, num_intervals)
print(power_profile)

[35.58780901 26.29157135 29.04706348 ... 34.78964365 21.68399644
 44.45578774]


In [14]:
# reshape the array into daily half hour profiles
num_daily = 24*2
daily = power_profile.reshape(365, num_daily)

print(daily)

[[35.58780901 26.29157135 29.04706348 ...  8.73475759  3.02924545
   1.31489271]
 [18.98859432 18.78161857 27.74554904 ...  6.33357222 34.44850792
  28.04771312]
 [46.28888506  2.74441232  4.55654867 ... 31.6347737  33.4335743
  18.18219041]
 ...
 [37.15179414 27.21426006 27.80189788 ... 11.9842643  30.63665664
  37.08208581]
 [ 0.13810171 33.14875514 14.69934454 ...  5.2867024  39.38467011
  44.85040504]
 [38.53140953 11.01151135 21.20278339 ... 34.78964365 21.68399644
  44.45578774]]


In [15]:
# convert to energy
daily*0.5

array([[17.79390451, 13.14578567, 14.52353174, ...,  4.36737879,
         1.51462273,  0.65744635],
       [ 9.49429716,  9.39080929, 13.87277452, ...,  3.16678611,
        17.22425396, 14.02385656],
       [23.14444253,  1.37220616,  2.27827434, ..., 15.81738685,
        16.71678715,  9.09109521],
       ...,
       [18.57589707, 13.60713003, 13.90094894, ...,  5.99213215,
        15.31832832, 18.5410429 ],
       [ 0.06905086, 16.57437757,  7.34967227, ...,  2.6433512 ,
        19.69233505, 22.42520252],
       [19.26570476,  5.50575567, 10.6013917 , ..., 17.39482182,
        10.84199822, 22.22789387]])

# Pandas
Pandas is the go-to for data processing in python. (it is built on Numpy).

Pandas provides tabular data structures for high-performance functions to analyse, clean, explore, and manipulate ‘big’ multidimensional and heterogeneous data.

Think of Pandas data structures like you would a spreadsheet (like in Excel) or an SQL table – but faster, easier and more powerful.

Pandas has two core data structures:

**Series** - A one-dimensional labelled homogeneous array containing data of any type. It is similar to a list, but has additional features such as indexing, slicing, and missing value handling. 

**DataFrame** - A two-dimensional, labelled, and heterogeneous tabular data structure with its own indexing system.

First, lets make sure pandas has been imported:

In [9]:
import pandas as pd

## Let's work with Pandas Dataframes
The first step will involve you creating a hypothetical dataframe and then you will move on to importing energy data with Pandas to perform basic descriptive statistics.

There are many ways to create a DataFrame, from scratch, most closely resemble a python dictionary with nested lists.

In [10]:
df = pd.DataFrame({"Country": ["Namibia", "Portugal", "Egypt", "Haiti", "Thailand", "Bolivia", "Estonia"],
                   "Primary Energy Consumption (TWh)": [22, 258, 1105, 12, 1406, 85, 62]})
df

Country  Primary Energy Consumption (TWh)
0   Namibia                                22
1  Portugal                               258
2     Egypt                              1105
3     Haiti                                12
4  Thailand                              1406
5   Bolivia                                85
6   Estonia                                62

### Creating your own data and placing it into a Pandas dataframe   

1. Using data from [OurWorldInData](https://ourworldindata.org/grapher/primary-sub-energy-source?tab=table)), create a DataFrame for your group’s country which contains the primary energy consumption by source for at least 3 year and at least 3 sources.

     Your index should be the year, and your columns should be the energy source

2. Use the .mean() method to calculate the mean for your data. Try setting the 'axis' keyword to 0 or 1. What does it do?
3. Try plotting the data using the .plot() method..


In [16]:
# Develop your code here
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/Users/zhangcuicheng/Library/CloudStorage/Dropbox/Cuicheng/Academic/PhD/08_Coding/MSc-Python-Example/primary-sub-energy-source.csv')

In [25]:
print(df.columns)


Index(['Entity', 'Code', 'Year', 'Wind consumption - TWh',
       'Hydro consumption - TWh', 'Solar consumption - TWh',
       'Nuclear consumption - TWh', 'Biofuels consumption - TWh',
       'Other renewables (including geothermal and biomass) - TWh',
       'Coal consumption - TWh', 'Oil consumption - TWh',
       'Gas consumption - TWh'],
      dtype='object')


In [26]:
# Filter data for a specific country
country_data = df[df['Entity'] == 'Chile']

# Select the columns for years and energy sources
energy_data = country_data[['Year', 'Hydro consumption - TWh', 'Nuclear consumption - TWh', 'Coal consumption - TWh']]

# Set 'year' as the index
energy_data.set_index('Year', inplace=True)
energy_data = energy_data.loc[[2010, 2015, 2020]]
print(energy_data)


      Hydro consumption - TWh  Nuclear consumption - TWh  \
Year                                                       
2010                60.395134                        0.0   
2015                63.612060                        0.0   
2020                57.045450                        0.0   

      Coal consumption - TWh  
Year                          
2010               52.229164  
2015               85.054840  
2020               73.145775  


### There are a few ways of importing data into Python and Pandas makes it very convenient.  
  
Have a look at the code below to see two examples  
  
`import pandas as pd
df = pd.read_csv('filename.txt', sep=" ", header=None, names=["a","b","c"])`
  
Or  
  
`import pandas as pd 
df = pd.read_csv('file_location\filename.txt', delimiter = "\t")  # Can input a URL as well`



#### Go ahead and import the data

The code below will use a URL to import data on the power plants of the USA, using the simpliest form of input arguements to the Pandas `read_csv` function. Note how we imported Numpy as `np` and not Pandas as `pd`. Dataframes are conventionally called `df` in Python but you can rename to another logical variable name. 


In [33]:
# The following implies an internet connection of course
import pandas as pd
usa_gen = pd.read_csv('https://raw.githubusercontent.com/wri/global-power-plant-database/master/source_databases_csv/database_USA.csv')


#### Let's have a look at the data

The `head` function is an easy way to inspect your dataset. The default number of rows to show is 5. Let's explore the dataset a bit. Use `df.head(20)` to see more rows etc. 
  
  

In [31]:
usa_gen.head(10)

country              country_long                             name  \
0     USA  United States of America   10 Briggs Solar NG  LLC (East)   
1     USA  United States of America       100 Brook Hill Drive Solar   
2     USA  United States of America       1001 Ebenezer Church Solar   
3     USA  United States of America              1008 Matthews Solar   
4     USA  United States of America                1009 Yadkin Solar   
5     USA  United States of America        1025 Traveller Solar  LLC   
6     USA  United States of America           1045 Tomlin Mill Solar   
7     USA  United States of America  1047 Little Mountain Solar  LLC   
8     USA  United States of America                1073 Onslow Solar   
9     USA  United States of America           12 Applegate Solar LLC   

    gppd_idnr  capacity_mw  latitude  longitude primary_fuel other_fuel1  \
0  USA0062781          0.0   41.6327   -71.4963          NaN         NaN   
1  USA0063292          2.0   41.0930   -73.9828        Solar         NaN   
2  USA0063444          0.0   36.2838   -80.8434          NaN         NaN   
3  USA0063447          0.0   36.2167   -80.5525          NaN         NaN   
4  USA0063445          0.0   36.1475   -80.6561          NaN         NaN   
5  USA0062660          5.0   35.4273   -79.1263        Solar         NaN   
6  USA0063448          0.0   35.9162   -80.8355          NaN         NaN   
7  USA0062661          3.0   36.1971   -80.8067        Solar         NaN   
8  USA0063446          0.0   34.7736   -77.1858          NaN         NaN   
9  USA0059371          1.9   40.2003   -74.5761        Solar         NaN   

  other_fuel2  ... year_of_capacity_data  generation_gwh_2013  \
0         NaN  ...                2019.0                  NaN   
1         NaN  ...                2019.0                  NaN   
2         NaN  ...                2019.0                  NaN   
3         NaN  ...                2019.0                  NaN   
4         NaN  ...                2019.0                  NaN   
5         NaN  ...                2019.0                  NaN   
6         NaN  ...                2019.0                  NaN   
7         NaN  ...                2019.0                  NaN   
8         NaN  ...                2019.0                  NaN   
9         NaN  ...                2019.0              2.41461   

  generation_gwh_2014 generation_gwh_2015 generation_gwh_2016  \
0                 NaN                 NaN                 NaN   
1                 NaN                 NaN                 NaN   
2                 NaN                 NaN                 NaN   
3                 NaN                 NaN                 NaN   
4                 NaN                 NaN                 NaN   
5                 NaN                 NaN                 NaN   
6                 NaN                 NaN                 NaN   
7                 NaN                 NaN                 NaN   
8                 NaN                 NaN                 NaN   
9                2.35                2.43               2.492   

  generation_gwh_2017  generation_gwh_2018  generation_gwh_2019  \
0                 NaN                  NaN                  NaN   
1                 NaN                  NaN                2.467   
2                 NaN                  NaN                  NaN   
3                 NaN                  NaN                  NaN   
4                 NaN                  NaN                  NaN   
5                 NaN                  NaN                1.332   
6                 NaN                  NaN                  NaN   
7                 NaN                  NaN                1.417   
8                 NaN                  NaN                  NaN   
9               2.276                2.207                2.349   

                   generation_data_source  estimated_generation_gwh  
0                                     NaN                       NaN  
1  U.S. Energy Information Administration                     

### Indexing with Pandas
There are many ways to index

In [36]:
# dot notation
df.country_long 

AttributeError: 'DataFrame' object has no attribute 'country_long'

In [ ]:
# or using square brackets
df["Primary Energy Consumption (TWh)"].head(3)  

In [ ]:
# or using the .loc function
df.loc[2:4, "Country"]

In [ ]:
# you can also use conditional statements to index
df[df["Primary Energy Consumption (TWh)"] > 100]

In [ ]:
# or use for loops to iterate through an axis
for i, row in df.iterrows():
    print(row["Country"])

**Your turn.** Let's pull some data from the `usa_gen` DataFrame that we have loaded based on some of the information given to you through the graphic above. *Hint: It is best to only use the data that you need.
&nbsp;

**Use the cells below to print the following values:**

1. The total number of power plants in the US.
2. The minimum, maximum and average capacity of the plants in MW.
3. The number of listed solar farms.
4. The number of different plant types listed.
5. The year with the highest generation from all of the plants.

In [37]:
# The total number of power plants in the US with capacity greater than 5MW.
total_plants = usa_gen['plant_name'].nunique()
print("Total number of power plants in the US:", total_plants)

KeyError: 'plant_name'

In [ ]:
# The minimum, maximum and average capacity of the plants in MW.

In [ ]:
# The number of listed solar farms.

In [ ]:
# The number of different plant types listed.

In [ ]:
# The year with the highest generation from all of the plants.

### Statistics, plotting etc
Pandas also provides lots of functions that can be used for statistical analysis and plotting (and many more) of large datasets

In [ ]:
# to calculate some summary statistics on the USA power plant capacity data
usa_gen["capacity_mw"].describe()

In [ ]:
# to plot capacity vs commissioning year
usa_gen.plot(x="commissioning_year", y="capacity_mw", kind='scatter')

Try changing the variables and type of plot produced to investigate other features in the data.

  
#### Animation and Code Sources  

*Datafram GIF: <a href="https://i.stack.imgur.com/aClG1.gif">Stack Exchange</a>   
Numpy GIF: <a href="https://matteding.github.io/images/broadcasting-3d-scalar.gif">Matt Eding</a>  
Final Challenge: <a href="https://dribbble.com/antoshenbka">Anton</a>   
Reach the finish line: <a href="https://i.pinimg.com/originals/5f/f8/8f/5ff88fa577c8b0fa614f2fa3747acf25.gif">Lidia R</a>*
